var myString;
var myNum;
var myBool;
var myVar;
// let strArr[] = [];
// let numArr[] = [];
// let boolArr[] = [];
var strArr;
var numArr;
var boolArr;
var strNumTuple;
myString = 'Hello' + '======' + 'there.';
myNum = 22;
myBool = false;
strArr = ['HELLO', 'WORLD'];
numArr = [1, 2, 3];
boolArr = [true, false, true];
strNumTuple = ['Hello', 4, 5, 6];
var myVoid = undefined;
var myNull = null;
var myUnfdefined = null;
myVar = 'false';
console.log(myVoid);
